/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espe.edu.ec.math.geometry.shapes.quadrilaterals;

import espe.edu.ec.math.geometry.shapes.circunference.*;
import ec.edu.espe.math.geometry.shapes.circunferences.Ellipse;
import ec.edu.espe.math.geometry.shapes.quadrilaterals.Rectangle;
import ec.edu.espe.math.geometry.shapes.quadrilaterals.Rhombus;
import ec.edu.espe.math.geometry.shapes.quadrilaterals.Romboide;
import ec.edu.espe.math.geometry.shapes.quadrilaterals.Square;

/**
 *
 * @author CASA
 */
public class QuadrilateralsRomboide extends javax.swing.JFrame {

    /**
     * Creates new form Circle
     */
    public QuadrilateralsRomboide() {
        initComponents();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtRadio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LblPerimeter = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtRadio1 = new javax.swing.JTextField();
        TxtRadio2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TxtRadio.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        getContentPane().add(TxtRadio);
        TxtRadio.setBounds(110, 80, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 90, 20);

        lblArea.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblArea);
        lblArea.setBounds(130, 200, 100, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Perimeter:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 100, 20);

        LblPerimeter.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LblPerimeter.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LblPerimeter);
        LblPerimeter.setBounds(130, 220, 100, 20);

        btnCalcular.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/calc.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(230, 250, 130, 41);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Quadrilaterals Romboide");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 250, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/shapes.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 70, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Diagonal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 60, 90, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Small:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 90, 90, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Height:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 170, 90, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Big:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 120, 50, 30);

        TxtRadio1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        getContentPane().add(TxtRadio1);
        TxtRadio1.setBounds(110, 120, 170, 30);

        TxtRadio2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        getContentPane().add(TxtRadio2);
        TxtRadio2.setBounds(110, 160, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 370, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
float Sidea,Sideb,Sidec;

Sidea=Float.parseFloat(TxtRadio.getText());
Sideb=Float.parseFloat(TxtRadio1.getText());
Sidec=Float.parseFloat(TxtRadio2.getText());


Romboide _Obj = new Romboide(Sidea,Sideb,Sidec);
        lblArea.setText(_Obj.area().toString());
        LblPerimeter.setText(_Obj.perimeter().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsRomboide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsRomboide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsRomboide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsRomboide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuadrilateralsRomboide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPerimeter;
    private javax.swing.JTextField TxtRadio;
    private javax.swing.JTextField TxtRadio1;
    private javax.swing.JTextField TxtRadio2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblArea;
    // End of variables declaration//GEN-END:variables
}
