/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espe.edu.ec.math.geometry.shapes.circunference;

import ec.edu.espe.math.geometry.shapes.circunferences.Circle;

/**
 *
 * @author CASA
 */
public class CircunferenceCircle extends javax.swing.JFrame {

    /**
     * Creates new form Circle
     */
    public CircunferenceCircle() {
        initComponents();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtRadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LblPerimeter = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboIn = new javax.swing.JComboBox();
        cboOut = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TxtRadio.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        getContentPane().add(TxtRadio);
        TxtRadio.setBounds(100, 70, 170, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Radio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 90, 20);

        lblArea.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblArea);
        lblArea.setBounds(140, 150, 100, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Perimeter:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 170, 100, 20);

        LblPerimeter.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        LblPerimeter.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LblPerimeter);
        LblPerimeter.setBounds(140, 170, 100, 20);

        btnCalcular.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/calc.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(260, 160, 130, 41);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Circunference Circle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 230, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/shapes.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 10, 70, 60);

        cboIn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cboIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mm", "Cm", "Dc", "M", "Km", "Ml", "yd", "Ft" }));
        cboIn.setSelectedIndex(3);
        getContentPane().add(cboIn);
        cboIn.setBounds(290, 70, 70, 30);

        cboOut.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cboOut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mm", "Cm", "Dc", "M", "Km", "Ml", "yd", "Ft" }));
        cboOut.setSelectedIndex(3);
        getContentPane().add(cboOut);
        cboOut.setBounds(10, 120, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 400, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
float Radio;

Radio=Float.parseFloat(TxtRadio.getText());
Circle _Circle = new Circle(Radio);
        lblArea.setText(_Circle.area().toString());
        LblPerimeter.setText(_Circle.perimeter().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircunferenceCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircunferenceCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircunferenceCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircunferenceCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircunferenceCircle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPerimeter;
    private javax.swing.JTextField TxtRadio;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox cboIn;
    private javax.swing.JComboBox cboOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblArea;
    // End of variables declaration//GEN-END:variables
}
