/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espe.edu.ec.math.geometry;

import espe.edu.ec.math.geometry.shapes.Shapes;
import espe.edu.ec.math.geometry.soilds.Soilds;

/**
 *
 * @author CASA
 */
public class Graphics extends javax.swing.JFrame {

    /**
     * Creates new form Graphics
     */
    public Graphics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnShapes = new javax.swing.JButton();
        BtnSoilds = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/soild.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 80, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espe.edu.ec.images/shapes.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 10, 80, 70);

        btnShapes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnShapes.setText("Shapes");
        btnShapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShapesActionPerformed(evt);
            }
        });
        getContentPane().add(btnShapes);
        btnShapes.setBounds(40, 90, 90, 33);

        BtnSoilds.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        BtnSoilds.setText("Soilds");
        BtnSoilds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSoildsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSoilds);
        BtnSoilds.setBounds(180, 90, 90, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShapesActionPerformed
new Shapes().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShapesActionPerformed

    private void BtnSoildsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSoildsActionPerformed
new Soilds().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSoildsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSoilds;
    private javax.swing.JButton btnShapes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
